engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
  flog:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/FrozenStringLiteralComment:
        enabled: false
