Documentation:
  Enabled: false
Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be an Integer or
  # a Float.
  Max: 15
  Exclude:
    - 'app/controllers/api/v1/sessions_controller.rb'

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 200

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 200

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Max: 6
  Exclude:
    - 'app/controllers/api/v1/sessions_controller.rb'

Metrics/LineLength:
  Max: 100
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 24
  Exclude:
    - 'app/controllers/api/v1/sessions_controller.rb'

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 12
  Exclude:
    - 'app/controllers/api/v1/sessions_controller.rb'

SingleSpaceBeforeFirstArg:
 Exclude:
   - app/views/api/**/**/*
