inherit_from:
  - .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - bin/yarn
    - config/initializers/pagy.rb
    - db/schema.rb
    - node_modules/**/*

Layout/ClassStructure:
  Enabled: true

Layout/LineLength:
  Exclude:
    - db/**/*

Layout/SpaceBeforeFirstArg:
  AllowForAlignment: true

Lint/AmbiguousBlockAssociation:
  AllowedMethods: change

Metrics/AbcSize:
  Max: 15
  Exclude:
    - db/**/*

Metrics/BlockLength:
  Exclude:
    - app/admin/**/*
    - config/**/*
    - spec/**/*

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 6

Metrics/MethodLength:
  Max: 24

Metrics/ModuleLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 12

Rails/SaveBang:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/HashLikeCase:
  MinBranchesCount: 4

Style/ModuleFunction:
  Enabled: false

Style/ReturnNil:
  Enabled: true

Style/StringConcatenation:
  Enabled: false
