inherit_from:
  - .rubocop-rs-config.yml
  - .rubocop-excludes.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails 
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - config/initializers/pagy.rb
    - bin/bundle
    - bin/yarn
    - node_modules/**/*
