version: '3.0'

services:
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST: db
    volumes:
      - .:/src/app
    depends_on:
      - db
      - chrome-server
    links:
      - db:db
  chrome-server:
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444
      - 7900:7900
      - 5900:5900
  spring:
    build: .
    volumes:
      - .:/src/app
    command: bundle exec spring server
  js:
    build: .
    command: yarn build --watch
    volumes:
      - .:/src/app
      - node_modules:/src/app/node_modules
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db_data:
  node_modules:
