version: '3.0'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST: db
      SELENIUM_BROWSER: remote
      SELENIUM_BROWSER_HOST: http://chrome-server:4444
      HEADLESS: true
    command: ./bin/dev
    tty: true
    stdin_open: true
    develop:
      watch:
        - action: sync
          path: .
          target: /src/app
        - action: rebuild
          path: package.json
        - action: rebuild
          path: Gemfile
    depends_on:
      - db
      - chrome-server
    links:
      - db:db
  chrome-server:
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444
      - 7900:7900
      - 5900:5900
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db_data:
