default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  # password: <%= ENV.fetch('POSTGRES_PASSWORD', 'Musash8606') %>
  # host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  # port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>

development:
  <<: *default
  database: helpout
  url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis") %>

test:
  <<: *default
  database: helpout_test
  # database: rails_api_base_test <%= ENV['TEST_ENV_NUMBER'] %>
  url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis") %>

# For production is recommended to set DATABASE_URL env variable.
# It will take precedence over the config defined here.
# https://edgeguides.rubyonrails.org/configuring.html#connection-preference
production:
  <<: *default
  database: db/development
  url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis") %>
